stages:
  - update_patched_master

variables:
  GIT_STRATEGY: fetch
  GIT_SSL_NO_VERIFY: "1"

update_patched_master:
  stage: update_patched_master
  only:
    - patched_changes
  script:
    - apk add --no-cache git
stages:
  - update_patched_master

update_patched_master:
  stage: update_patched_master
  only:
    - patched_changes
  script:
    - echo "Cloning repository locally..."
    - git clone ${CI_PROJECT_DIR} /tmp/repo
    - cd /tmp/repo
    - echo "Checking out patched_master branch..."
    - git checkout patched_master || git checkout -b patched_master
    - echo "Resetting patched_master to patched_changes..."
    - git reset --hard origin/patched_changes
    - echo "Pushing updated patched_master branch..."
    - git push origin patched_master --force
