stages:
  - update_patched_master

variables:
  GIT_STRATEGY: fetch
  GIT_SSL_NO_VERIFY: "1"

update_patched_master:
  stage: update_patched_master
  only:
    - patched_changes
  script:
    - apk add --no-cache git
    - git config user.name "$GITLAB_USER_NAME"
    - git config user.email "$GITLAB_USER_EMAIL"
    - git remote set-url origin http://oauth2:${GITLAB_ACCESS_TOKEN}@172.17.0.1:4411/${CI_PROJECT_PATH}.git
    - echo "Fetching all branches..."
    - git fetch --all
    - echo "Checking out patched_master..."
    - git checkout patched_master
    - echo "Merging master into patched_master, favoring patched_changes..."
    - git merge -s recursive -X theirs origin/master
    - echo "Cleaning up after merge..."
    - git add .
    - echo "Committing resolved merge..."
    - git commit -m "Auto-resolve merge conflicts Favor patched_changes"
    - echo "Pushing changes to patched_master..."
    - git push origin patched_master
