stages:
  - update_patched_master

variables:
  GIT_STRATEGY: fetch
  GIT_SSL_NO_VERIFY: "1"

update_patched_master:
  stage: update_patched_master
  only:
    - patched_changes
  script:
    - git config user.name "$GITLAB_USER_NAME"
    - git config user.email "$GITLAB_USER_EMAIL"
    - git remote set-url origin http://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab/${CI_PROJECT_PATH}.git
    - git fetch --all
    - git checkout patched_master
    - git merge origin/master --no-edit
    - git rm -r --cached .
    - git clean -fd
    - git checkout origin/patched_changes -- . ':!.gitlab-ci.yml'
    - git add .
    - git commit -m "Auto-update patched_master with changes from patched_changes"
    - git push origin patched_master
