stages:
  - update_patched_master

update_patched_master:
  stage: update_patched_master
  only:
    - patched_changes
  script:
    - apk --no-cache add git
    - git fetch origin
    - git checkout patched_master || git checkout -b patched_master
    - git reset --hard origin/patched_changes
    - git push origin patched_master --force
